import Head from 'next/head'
import Link from 'next/link'

export default function Home () {
  return (
    <>
      <Head>
        <title>Prueba técnica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='containter'>
          <div className='row'>
            <h1 className='text-center mt-4'>Prueba técnica frontend</h1>
            <p className='font-monospace text-center'>
              Developer: Jose Daniel Posso Garcia (@daniel7byte)
              <br />
              GitHub: <a href='https://github.com/daniel7byte/technical-test-frontend'>https://github.com/daniel7byte/technical-test-frontend</a>
            </p>
            <div className='text-center'>
              <Link href={'/products/1'} className={'btn btn-danger text-white bg-red-wine mt-3'}>
                Ir a la página
              </Link>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
