import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>Prueba técnica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='containter'>
          <div className='row'>
            <h1 className='text-center mt-4'>Prueba técnica frontend</h1>
            <p className='font-monospace text-center'>
              Developer: Jose Daniel Posso Garcia (@daniel7byte)
              <br />
              GitHub: <a href='https://github.com/daniel7byte/technical-test-frontend'>https://github.com/daniel7byte/technical-test-frontend</a>
            </p>
            <Link href={'/products/1'} className={'text-center mt-3 buttom btn-primary'}>
              <button type="button" class="btn text-white bg-red-wine">Ir a la página</button>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
